environments:
  dev:
    variables:
      - name: TEST_ENV
        value:
          gcloud_secret:
            name: projects/603089349237/secrets/test/versions/latest
            # validate_crc32c: true
  
#    files:
#      - name: SECRETMANAGER_VAR_FILE
#        content:
#          gcloud_secret:
#            name: projects/my-project/secrets/SomeSecret/versions/latest
